export enum STATUS_CODE_ENUM {
  INTERNAL_SERVER_ERROR = 500,
  Ok = 200,
  CREATED = 201,
  BAD_REQUEST = 404,
  UNATUHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  INTERNAL_SERVER = 500,
  FAILED_DEPENDENCY = 424,
  NOT_MODIFIED = 304,
  PARTIAL_CONTENT = 206,
}

export interface I_ERROR_MAP {
  errorCode: ERROR_CODE_ENUM;
  message: string;
  statusCode: STATUS_CODE_ENUM;
}

export enum ERROR_CODE_ENUM {
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  INVALID_ACTION_TYPE = "INVALID_ACTION_TYPE",
  INVALID_RESOURCE_TYPE = "INVALID_RESOURCE_TYPE",
  INVALID_PAYLOAD = "INVALID_PAYLOAD",
  SCOPE_MISSING = "SCOPE_MISSING",
  DUPLICATE_RESOURCE = "DUPLICATE_RESOURCE",
  FILE_NOT_FOUND_TO_DOWNLOAD = "FILE_NOT_FOUND_TO_DOWNLOAD",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}

export const ERROR_MAP = {};
